// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class Activity
{
    public Guid Id { get; set; }

    public Guid GroupId { get; set; }

    public string Name { get; set; }

    public DateOnly ActivityDate { get; set; }

    public string Notes { get; set; }

    public bool IsActive { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual LoginUser CreatedByNavigation { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual AppGroup Group { get; set; }

    public virtual SettlementRun SettlementRun { get; set; }
}