// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class Expense
{
    public Guid Id { get; set; }

    public Guid ActivityId { get; set; }

    public Guid PayerPersonId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public bool IncludePayer { get; set; }

    public string Note { get; set; }

    public Guid? LockedInRunId { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual LoginUser CreatedByNavigation { get; set; }

    public virtual Person PayerPerson { get; set; }

    public virtual ICollection<SettlementExpenseAllocation> SettlementExpenseAllocations { get; set; } = new List<SettlementExpenseAllocation>();

    public virtual ICollection<Family> Families { get; set; } = new List<Family>();

    public virtual ICollection<Person> People { get; set; } = new List<Person>();
}