// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class Payment
{
    public Guid Id { get; set; }

    public Guid RunId { get; set; }

    public Guid PayerPersonId { get; set; }

    public Guid PayeePersonId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public DateTime PaidAt { get; set; }

    public string Reference { get; set; }

    public virtual Person PayeePerson { get; set; }

    public virtual Person PayerPerson { get; set; }

    public virtual SettlementRun Run { get; set; }
}