// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class PersonFactor
{
    public Guid Id { get; set; }

    public Guid PersonId { get; set; }

    public decimal Factor { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ValidFactor FactorNavigation { get; set; }

    public virtual Person Person { get; set; }
}