// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class Person
{
    public Guid Id { get; set; }

    public Guid FamilyId { get; set; }

    public string FullName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual Family Family { get; set; }

    public virtual ICollection<Payment> PaymentPayeePeople { get; set; } = new List<Payment>();

    public virtual ICollection<Payment> PaymentPayerPeople { get; set; } = new List<Payment>();

    public virtual PersonFactor PersonFactor { get; set; }

    public virtual ICollection<SettlementExpenseAllocation> SettlementExpenseAllocations { get; set; } = new List<SettlementExpenseAllocation>();

    public virtual ICollection<SettlementLine> SettlementLines { get; set; } = new List<SettlementLine>();

    public virtual ICollection<Expense> ExpensesNavigation { get; set; } = new List<Expense>();

    public virtual ICollection<LoginUser> Users { get; set; } = new List<LoginUser>();
}