// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class SettlementLine
{
    public Guid Id { get; set; }

    public Guid RunId { get; set; }

    public Guid PersonId { get; set; }

    public decimal OwedTotal { get; set; }

    public decimal CreditTotal { get; set; }

    public decimal NetAmount { get; set; }

    public decimal AmountPaid { get; set; }

    public string Currency { get; set; }

    public virtual Person Person { get; set; }

    public virtual SettlementRun Run { get; set; }
}