// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class SettlementRun
{
    public Guid Id { get; set; }

    public Guid ActivityId { get; set; }

    public int RunNo { get; set; }

    public Guid? ExecutedBy { get; set; }

    public DateTime ExecutedAt { get; set; }

    public DateTime? FinalizedAt { get; set; }

    public int ExpensesCount { get; set; }

    public decimal TotalExpenses { get; set; }

    public decimal TotalAllocated { get; set; }

    public string Notes { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual LoginUser ExecutedByNavigation { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<SettlementExpenseAllocation> SettlementExpenseAllocations { get; set; } = new List<SettlementExpenseAllocation>();

    public virtual ICollection<SettlementLine> SettlementLines { get; set; } = new List<SettlementLine>();
}