// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class SettlementExpenseAllocation
{
    public Guid Id { get; set; }

    public Guid RunId { get; set; }

    public Guid ExpenseId { get; set; }

    public Guid PersonId { get; set; }

    public decimal WeightUsed { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public virtual Expense Expense { get; set; }

    public virtual Person Person { get; set; }

    public virtual SettlementRun Run { get; set; }
}