// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class UserRoleAssignment
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid? GroupId { get; set; }

    public Guid? FamilyId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Family Family { get; set; }

    public virtual AppGroup Group { get; set; }

    public virtual LoginUser User { get; set; }
}