// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrewConnect.Domain.Models;

public partial class ValidFactor
{
    public decimal Value { get; set; }

    public virtual ICollection<PersonFactor> PersonFactors { get; set; } = new List<PersonFactor>();
}