// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using CrewConnect.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace CrewConnect.Infrastructure;

public partial class CrewConnectDbContext : DbContext
{
    public CrewConnectDbContext(DbContextOptions<CrewConnectDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<AppGroup> AppGroups { get; set; }

    public virtual DbSet<Expense> Expenses { get; set; }

    public virtual DbSet<Family> Families { get; set; }

    public virtual DbSet<LoginUser> LoginUsers { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<PersonFactor> PersonFactors { get; set; }

    public virtual DbSet<RoleDefinition> RoleDefinitions { get; set; }

    public virtual DbSet<SettlementExpenseAllocation> SettlementExpenseAllocations { get; set; }

    public virtual DbSet<SettlementLine> SettlementLines { get; set; }

    public virtual DbSet<SettlementRun> SettlementRuns { get; set; }

    public virtual DbSet<UserRoleAssignment> UserRoleAssignments { get; set; }

    public virtual DbSet<ValidFactor> ValidFactors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("expense_status", new[] { "draft", "active", "locked", "void" })
            .HasPostgresEnum("expense_target_scope", new[] { "GROUP", "FAMILIES", "PERSONS" })
            .HasPostgresEnum("payment_status", new[] { "unpaid", "partial", "paid" })
            .HasPostgresEnum("role_key", new[] { "admin", "group_admin", "family_admin", "member", "viewer" })
            .HasPostgresEnum("role_scope", new[] { "GROUP", "FAMILY" })
            .HasPostgresEnum("settlement_run_status", new[] { "pending", "finalized", "canceled" })
            .HasPostgresExtension("btree_gist")
            .HasPostgresExtension("citext")
            .HasPostgresExtension("pgcrypto");

        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("activity_pkey");

            entity.ToTable("activity");

            entity.HasIndex(e => e.ActivityDate, "ix_activity_date");

            entity.HasIndex(e => e.GroupId, "ix_activity_group");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.ActivityDate).HasColumnName("activity_date");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name).HasColumnName("name");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Activities)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("activity_created_by_fkey");

            entity.HasOne(d => d.Group).WithMany(p => p.Activities)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("activity_group_id_fkey");
        });

        modelBuilder.Entity<AppGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("app_group_pkey");

            entity.ToTable("app_group");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .HasDefaultValueSql("'USD'::bpchar")
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name).HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<Expense>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("expense_pkey");

            entity.ToTable("expense");

            entity.HasIndex(e => e.ActivityId, "ix_expense_activity");

            entity.HasIndex(e => e.LockedInRunId, "ix_expense_locked_run");

            entity.HasIndex(e => e.PayerPersonId, "ix_expense_payer");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.ActivityId).HasColumnName("activity_id");
            entity.Property(e => e.Amount)
                .HasPrecision(12, 2)
                .HasColumnName("amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .HasDefaultValueSql("'USD'::character(3)")
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.IncludePayer)
                .HasDefaultValue(true)
                .HasColumnName("include_payer");
            entity.Property(e => e.LockedInRunId).HasColumnName("locked_in_run_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.PayerPersonId).HasColumnName("payer_person_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Activity).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.ActivityId)
                .HasConstraintName("expense_activity_id_fkey");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("expense_created_by_fkey");

            entity.HasOne(d => d.PayerPerson).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.PayerPersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("expense_payer_person_id_fkey");

            entity.HasMany(d => d.Families).WithMany(p => p.Expenses)
                .UsingEntity<Dictionary<string, object>>(
                    "ExpenseFamilyTarget",
                    r => r.HasOne<Family>().WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("expense_family_target_family_id_fkey"),
                    l => l.HasOne<Expense>().WithMany()
                        .HasForeignKey("ExpenseId")
                        .HasConstraintName("expense_family_target_expense_id_fkey"),
                    j =>
                    {
                        j.HasKey("ExpenseId", "FamilyId").HasName("expense_family_target_pkey");
                        j.ToTable("expense_family_target");
                        j.IndexerProperty<Guid>("ExpenseId").HasColumnName("expense_id");
                        j.IndexerProperty<Guid>("FamilyId").HasColumnName("family_id");
                    });

            entity.HasMany(d => d.People).WithMany(p => p.ExpensesNavigation)
                .UsingEntity<Dictionary<string, object>>(
                    "ExpensePersonTarget",
                    r => r.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("expense_person_target_person_id_fkey"),
                    l => l.HasOne<Expense>().WithMany()
                        .HasForeignKey("ExpenseId")
                        .HasConstraintName("expense_person_target_expense_id_fkey"),
                    j =>
                    {
                        j.HasKey("ExpenseId", "PersonId").HasName("expense_person_target_pkey");
                        j.ToTable("expense_person_target");
                        j.IndexerProperty<Guid>("ExpenseId").HasColumnName("expense_id");
                        j.IndexerProperty<Guid>("PersonId").HasColumnName("person_id");
                    });
        });

        modelBuilder.Entity<Family>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("family_pkey");

            entity.ToTable("family");

            entity.HasIndex(e => e.GroupId, "ix_family_group");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name).HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Group).WithMany(p => p.Families)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("family_group_id_fkey");
        });

        modelBuilder.Entity<LoginUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("login_user_pkey");

            entity.ToTable("login_user");

            entity.HasIndex(e => e.Email, "login_user_email_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DisplayName).HasColumnName("display_name");
            entity.Property(e => e.Email)
                .HasColumnType("citext")
                .HasColumnName("email");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasMany(d => d.People).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserPersonLink",
                    r => r.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonId")
                        .HasConstraintName("user_person_link_person_id_fkey"),
                    l => l.HasOne<LoginUser>().WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_person_link_user_id_fkey"),
                    j =>
                    {
                        j.HasKey("UserId", "PersonId").HasName("user_person_link_pkey");
                        j.ToTable("user_person_link");
                        j.IndexerProperty<Guid>("UserId").HasColumnName("user_id");
                        j.IndexerProperty<Guid>("PersonId").HasColumnName("person_id");
                    });
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("payment_pkey");

            entity.ToTable("payment");

            entity.HasIndex(e => new { e.PayerPersonId, e.PayeePersonId }, "ix_payment_dir");

            entity.HasIndex(e => e.RunId, "ix_payment_run");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasPrecision(12, 2)
                .HasColumnName("amount");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.PaidAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("paid_at");
            entity.Property(e => e.PayeePersonId).HasColumnName("payee_person_id");
            entity.Property(e => e.PayerPersonId).HasColumnName("payer_person_id");
            entity.Property(e => e.Reference).HasColumnName("reference");
            entity.Property(e => e.RunId).HasColumnName("run_id");

            entity.HasOne(d => d.PayeePerson).WithMany(p => p.PaymentPayeePeople)
                .HasForeignKey(d => d.PayeePersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("payment_payee_person_id_fkey");

            entity.HasOne(d => d.PayerPerson).WithMany(p => p.PaymentPayerPeople)
                .HasForeignKey(d => d.PayerPersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("payment_payer_person_id_fkey");

            entity.HasOne(d => d.Run).WithMany(p => p.Payments)
                .HasForeignKey(d => d.RunId)
                .HasConstraintName("payment_run_id_fkey");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("person_pkey");

            entity.ToTable("person");

            entity.HasIndex(e => e.FamilyId, "ix_person_family");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.FamilyId).HasColumnName("family_id");
            entity.Property(e => e.FullName).HasColumnName("full_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Family).WithMany(p => p.People)
                .HasForeignKey(d => d.FamilyId)
                .HasConstraintName("person_family_id_fkey");
        });

        modelBuilder.Entity<PersonFactor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("person_factor_pkey");

            entity.ToTable("person_factor");

            entity.HasIndex(e => e.PersonId, "person_factor_person_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Factor)
                .HasPrecision(6, 4)
                .HasColumnName("factor");
            entity.Property(e => e.PersonId).HasColumnName("person_id");

            entity.HasOne(d => d.FactorNavigation).WithMany(p => p.PersonFactors)
                .HasForeignKey(d => d.Factor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_factor_factor_fkey");

            entity.HasOne(d => d.Person).WithOne(p => p.PersonFactor)
                .HasForeignKey<PersonFactor>(d => d.PersonId)
                .HasConstraintName("person_factor_person_id_fkey");
        });

        modelBuilder.Entity<RoleDefinition>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("role_definition");

            entity.Property(e => e.Description).HasColumnName("description");
        });

        modelBuilder.Entity<SettlementExpenseAllocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("settlement_expense_allocation_pkey");

            entity.ToTable("settlement_expense_allocation");

            entity.HasIndex(e => e.PersonId, "ix_sea_person");

            entity.HasIndex(e => e.RunId, "ix_sea_run");

            entity.HasIndex(e => new { e.RunId, e.ExpenseId, e.PersonId }, "settlement_expense_allocation_run_id_expense_id_person_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasPrecision(12, 2)
                .HasColumnName("amount");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.ExpenseId).HasColumnName("expense_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.RunId).HasColumnName("run_id");
            entity.Property(e => e.WeightUsed)
                .HasPrecision(6, 4)
                .HasColumnName("weight_used");

            entity.HasOne(d => d.Expense).WithMany(p => p.SettlementExpenseAllocations)
                .HasForeignKey(d => d.ExpenseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("settlement_expense_allocation_expense_id_fkey");

            entity.HasOne(d => d.Person).WithMany(p => p.SettlementExpenseAllocations)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("settlement_expense_allocation_person_id_fkey");

            entity.HasOne(d => d.Run).WithMany(p => p.SettlementExpenseAllocations)
                .HasForeignKey(d => d.RunId)
                .HasConstraintName("settlement_expense_allocation_run_id_fkey");
        });

        modelBuilder.Entity<SettlementLine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("settlement_line_pkey");

            entity.ToTable("settlement_line");

            entity.HasIndex(e => e.RunId, "ix_sl_run");

            entity.HasIndex(e => new { e.RunId, e.PersonId }, "settlement_line_run_id_person_id_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AmountPaid)
                .HasPrecision(12, 2)
                .HasColumnName("amount_paid");
            entity.Property(e => e.CreditTotal)
                .HasPrecision(12, 2)
                .HasColumnName("credit_total");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("currency");
            entity.Property(e => e.NetAmount)
                .HasPrecision(12, 2)
                .HasColumnName("net_amount");
            entity.Property(e => e.OwedTotal)
                .HasPrecision(12, 2)
                .HasColumnName("owed_total");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.RunId).HasColumnName("run_id");

            entity.HasOne(d => d.Person).WithMany(p => p.SettlementLines)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("settlement_line_person_id_fkey");

            entity.HasOne(d => d.Run).WithMany(p => p.SettlementLines)
                .HasForeignKey(d => d.RunId)
                .HasConstraintName("settlement_line_run_id_fkey");
        });

        modelBuilder.Entity<SettlementRun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("settlement_run_pkey");

            entity.ToTable("settlement_run");

            entity.HasIndex(e => e.ActivityId, "uq_finalized_run_per_activity")
                .IsUnique()
                .HasFilter("(status = 'finalized'::settlement_run_status)");

            entity.HasIndex(e => new { e.ActivityId, e.RunNo }, "uq_run_per_activity").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.ActivityId).HasColumnName("activity_id");
            entity.Property(e => e.ExecutedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("executed_at");
            entity.Property(e => e.ExecutedBy).HasColumnName("executed_by");
            entity.Property(e => e.ExpensesCount).HasColumnName("expenses_count");
            entity.Property(e => e.FinalizedAt).HasColumnName("finalized_at");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.RunNo).HasColumnName("run_no");
            entity.Property(e => e.TotalAllocated)
                .HasPrecision(14, 2)
                .HasColumnName("total_allocated");
            entity.Property(e => e.TotalExpenses)
                .HasPrecision(14, 2)
                .HasColumnName("total_expenses");

            entity.HasOne(d => d.Activity).WithOne(p => p.SettlementRun)
                .HasForeignKey<SettlementRun>(d => d.ActivityId)
                .HasConstraintName("settlement_run_activity_id_fkey");

            entity.HasOne(d => d.ExecutedByNavigation).WithMany(p => p.SettlementRuns)
                .HasForeignKey(d => d.ExecutedBy)
                .HasConstraintName("settlement_run_executed_by_fkey");
        });

        modelBuilder.Entity<UserRoleAssignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("user_role_assignment_pkey");

            entity.ToTable("user_role_assignment");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.FamilyId).HasColumnName("family_id");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Family).WithMany(p => p.UserRoleAssignments)
                .HasForeignKey(d => d.FamilyId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("ura_family_fk");

            entity.HasOne(d => d.Group).WithMany(p => p.UserRoleAssignments)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("user_role_assignment_group_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleAssignments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_role_assignment_user_id_fkey");
        });

        modelBuilder.Entity<ValidFactor>(entity =>
        {
            entity.HasKey(e => e.Value).HasName("valid_factor_pkey");

            entity.ToTable("valid_factor");

            entity.Property(e => e.Value)
                .HasPrecision(6, 4)
                .HasColumnName("value");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}