<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1a26b8f1-9b9b-47c9-8d5f-b9c6d026c30d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrewConnect.Web\CrewConnect.Web\CrewConnect.Web.csproj" />
    <ProjectReference Include="..\CrewConnect.Infrastructure\CrewConnect.Infrastructure.csproj" />
  </ItemGroup>

</Project>
